// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc31.Recycle.subsystems;

import org.usfirst.frc31.Recycle.RobotMap;
import org.usfirst.frc31.Recycle.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class ArmSystem extends Subsystem {
    Relay spike1 = RobotMap.spike1;
    Relay spike2 = RobotMap.spike2;
    
    public void initDefaultCommand() {
    	
    }
    
    public void spinArm(Joystick one)
    {
    	if (one.getRawButton(3))
    	{
        	spike1.set(Relay.Value.kOn);
        	spike2.set(Relay.Value.kOn);
    		spike1.set(Relay.Value.kReverse);
    		spike2.set(Relay.Value.kForward);
    	}
    	else
    	{
    		spike1.set(Relay.Value.kOff);
    		spike2.set(Relay.Value.kOff);
    	}
    }
}

