// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc31.Recycle.subsystems;

import org.usfirst.frc31.Recycle.RobotMap;
import org.usfirst.frc31.Recycle.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.ControlMode;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveSystem extends Subsystem {
	
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
	CANTalon talon3 = RobotMap.talon3;
	CANTalon talon4 = RobotMap.talon4;
	CANTalon talon5 = RobotMap.talon5;
	CANTalon talon6 = RobotMap.talon6;
	RobotDrive mainDrive = RobotMap.mainDrive;

    public void initDefaultCommand() {
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void takeJoystickInput(Joystick two)
    {
        mainDrive.mecanumDrive_Cartesian(two.getY(), two.getX(), -two.getZ(), 0);
    }
    
    public void goForward()
    {
    	talon4.set(.5);
    	talon6.set(.5);
//    	Timer.delay(5);
    }
}

